spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: yao123456
    url: "jdbc:mysql://localhost:3306/qrcodegenerator?useUnicode=true&characterEncoding=utf8"